"""PDF submission report generator — F10."""

import os
from pathlib import Path

from fpdf import FPDF

from config.settings import REPORTS_DIR
import db.database as db


def generate_run_report(run_id: str) -> str:
    """Generate a PDF report for a given run and return the file path."""
    history = db.get_run_history()
    run_rows = [r for r in history if r["run_id"] == run_id]

    if not run_rows:
        raise ValueError(f"No run found with run_id: {run_id}")

    first = run_rows[0]

    Path(REPORTS_DIR).mkdir(parents=True, exist_ok=True)
    out_path = os.path.join(REPORTS_DIR, f"run_{run_id[:8]}.pdf")

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 12, "VendorFlow AI - Onboarding Report", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, "Powered by TinyFish Web Agent API", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(6)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Run Details", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 7, f"Run ID: {run_id[:8]}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 7, f"Date: {first['started_at'][:19]}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 7, f"Total Portals: {first['portal_count']}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 7, f"Successful: {first['success_count']}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 7, f"Total Time: {first['total_time_seconds'] / 60:.1f} minutes", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Portal Results", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 10)
    col_widths = [55, 30, 30, 75]
    headers = ["Portal Name", "Status", "Time (min)", "Reference ID"]
    for i, h in enumerate(headers):
        pdf.cell(col_widths[i], 7, h, border=1)
    pdf.ln()

    pdf.set_font("Helvetica", "", 10)
    for row in run_rows:
        name = row.get("portal_name", "N/A") or "N/A"
        status = row.get("status", "N/A") or "N/A"
        time_val = f"{(row.get('time_taken_seconds') or 0) / 60:.1f}"
        ref = row.get("reference_id") or "-"
        pdf.cell(col_widths[0], 7, str(name)[:25], border=1)
        pdf.cell(col_widths[1], 7, str(status), border=1)
        pdf.cell(col_widths[2], 7, time_val, border=1)
        pdf.cell(col_widths[3], 7, str(ref)[:30], border=1)
        pdf.ln()

    pdf.ln(6)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    portal_count = first["portal_count"]
    total_seconds = first["total_time_seconds"]
    manual_hours = portal_count * 2.5
    cost_saved = manual_hours * 25

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "ROI Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 7, f"Estimated manual time: {manual_hours:.1f} hours", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 7, f"VendorFlow AI time: {total_seconds / 3600:.1f} hours", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 7, f"Estimated savings: ${cost_saved:,.0f} USD", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(0, 6, "Generated by VendorFlow AI | TinyFish Hackathon 2026", align="C")

    pdf.output(out_path)
    return out_path
